name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Build Go server
        run: make build/go

      - name: Build Java tests
        run: make build/java

      - name: Build docker image
        run: docker build . --file Dockerfile --tag grpc-server:test

      - name: Smoke test docker image
        run: |
          docker run -d -p 50051:50051 -p 2112:2112 --name grpc-server grpc-server:test
          sleep 5
          curl -f http://localhost:2112/metrics || exit 1
